version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm run start:dev
    restart: always
